# Generated by Django 2.2.2 on 2020-04-19 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_newspage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsPage',
        ),
    ]
