# Generated by Django 2.2.2 on 2020-04-19 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time_checked', models.DateTimeField()),
                ('website', models.TextField()),
                ('html_content', models.TextField()),
            ],
        ),
    ]
